# Generated by Django 2.2.7 on 2019-12-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='Vehicle_ins',
            new_name='vehicle_insurance',
        ),
    ]
